### PR TITLE
fix: -Werror=maybe-uninitialized in input.cpp

### PR DESCRIPTION
**Pull request by KMikeeU**

### CODE REVIEW

**Comment by Totto16** [comment]
@mgerhold  As I said, I always prefer tl::nullopt, for exact this reason :grin: (the same happened to me, since many types are default constructable b `{}`)

**Comment by mgerhold** [comment]
We can change it, but this is clearly a clang bug 🙁

**Comment by KMikeeU** [comment]
> We can change it, but this is clearly a clang bug slightly_frowning_face

Looking at the meson log, I think I'm using gcc (v12.2.1), not clang

**Comment by mgerhold** [comment]
> > We can change it, but this is clearly a clang bug slightly_frowning_face
> 
> Looking at the meson log, I think I'm using gcc (v12.2.1), not clang

Oh, okay 😂 Either way, I changed it 😅

**Pull request merged**
